### ISSUE TITLE
add keyrings

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-java#102]
Starting with the AWS Encryption SDK for C, we moved from master keys/providers to keyrings as a configuration/framework primitive. We need to add corresponding keyrings to this client as well.

See #150 for a discussion on the evolution of the API as we transition to Keyrings
See #153 for a discussion on the ergonomics of Keyrings

All keyring development PRs should be made to the `keyring` branch.

- [x] Create keyring trace and add to encryption and decryption materials #134
- [x] Keyring interface #142 
- [x] KMS keyring  #147 
- [x] Raw RSA keyring #142 
- [x] Raw AES keyring #142 
- [x] Multi keyring #148
- [x] ~~MasterKeyProvider keyring #149~~
- [x] ~Master Key Provider Keyring Spec: [#62](https://github.com/awslabs/aws-encryption-sdk-specification/pull/62)~
- [x] Incorporate Keyrings into AwsCrypto and deprecate MasterKeyProviders #151 
- [x] New example code for Keyrings #155
- [x] Ensure new JUnit 5 tests for Keyrings are being run as part of Travis #154 
- [x] Update Readme example code #156
- [ ] Update Changelog with new deprecation notice and Keyring features #174 
- [x] Merge to master branch #173
- [ ] Release to Maven
